import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next | Basics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.sectionhome}>
        <div>
          <Image
            src="/man.png"
            alt="man"
            width={200}
            height={200}
            blurDataURL="data..."
            placeholder="blur"
          />
          <p>HOST {process.env.NEXT_PUBLIC_HOST}</p>
          <p>DB_PASS: {process.env.NEXT_PUBLIC_DB_PASS}</p>
        </div>
      </section>
    </>
  );
}
